# [LXCFS]: LXCFS DaemonSet Configurations
lxcfs:
  daemonSet:
    image:
      repository: gpu-harbor.act.buaa.edu.cn/user-liyilong/ubuntu
      tag: "05061356-8213"
    resources:
      limits:
        cpu: 200m
        memory: 256Mi
      requests:
        cpu: 100m
        memory: 128Mi
    nodeSelector: {}
    tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
    affinity: {}
    hostPID: true
    securityContext:
      privileged: true
    lifecycle:
      postStart:
        enable: true
        logPath: /tmp/lxcfs
      preStop:
        enable: true
    volumeMounts:
      extraVolumeMounts: []
    volumes:
      extraVolumes: []
  configMaps:
    crictlConfig:
      enable: true
      endpoint: unix:///var/run/containerd/containerd.sock

# [MANAGER]: Manager Deployment Configurations
controllerManager:
  replicas: 1
  container:
    image:
      repository: crater-harbor.act.buaa.edu.cn/crater/lxcfs-webhook
      tag: v0.1
    args:
      - "--leader-elect"
      - "--health-probe-bind-address=:8081"
    resources:
      limits:
        cpu: 500m
        memory: 128Mi
      requests:
        cpu: 10m
        memory: 64Mi
    livenessProbe:
      initialDelaySeconds: 15
      periodSeconds: 20
      httpGet:
        path: /healthz
        port: 8081
    readinessProbe:
      initialDelaySeconds: 5
      periodSeconds: 10
      httpGet:
        path: /readyz
        port: 8081
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - "ALL"
  securityContext:
    runAsNonRoot: true
    seccompProfile:
      type: RuntimeDefault
  terminationGracePeriodSeconds: 10
  serviceAccountName: lxcfs-webhook-controller-manager

# [RBAC]: To enable RBAC (Permissions) configurations
rbac:
  enable: true

# [METRICS]: Set to true to generate manifests for exporting metrics.
# To disable metrics export set false, and ensure that the
# ControllerManager argument "--metrics-bind-address=:8443" is removed.
metrics:
  enable: false

# [WEBHOOKS]: Webhooks configuration
# The following configuration is automatically generated from the manifests
# generated by controller-gen. To update run 'make manifests' and
# the edit command with the '--force' flag
webhook:
  enable: true

# [PROMETHEUS]: To enable a ServiceMonitor to export metrics to Prometheus set true
prometheus:
  enable: false

# [CERT-MANAGER]: To enable cert-manager injection to webhooks set true
certmanager:
  enable: true

# [NETWORK POLICIES]: To enable NetworkPolicies set true
networkPolicy:
  enable: false
