apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
  - name: vpod-v1.kb.io
    namespaceSelector:
      matchLabels:
        lxcfs-admission-webhook: enabled
