apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: lxcfs
  namespace: {{ .Release.Namespace }}
  labels:
    app: lxcfs
    {{- include "chart.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app: lxcfs
      {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        app: lxcfs
        {{- include "chart.labels" . | nindent 8 }}
    spec:
      hostPID: {{ .Values.lxcfs.daemonSet.hostPID }}
      {{- with .Values.lxcfs.daemonSet.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lxcfs.daemonSet.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lxcfs.daemonSet.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: lxcfs
          image: {{ .Values.lxcfs.daemonSet.image.repository }}:{{ .Values.lxcfs.daemonSet.image.tag }}
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          lifecycle:
            {{- if .Values.lxcfs.daemonSet.lifecycle.postStart.enable }}
            postStart:
              exec:
                command:
                  - bash
                  - -c
                  - /opt/container_remount_lxcfs.sh > /opt/log/lxcfs.log 2>&1
            {{- end }}
            {{- if .Values.lxcfs.daemonSet.lifecycle.preStop.enable }}
            preStop:
              exec:
                command:
                  - bash
                  - -c
                  - nsenter -m/proc/1/ns/mnt fusermount -u /var/lib/lxc/lxcfs 2> /dev/null || true
            {{- end }}
          command:
            - sh
            - -c
            - /start.sh
          securityContext:
            {{- toYaml .Values.lxcfs.daemonSet.securityContext | nindent 12 }}
          resources:
            {{- toYaml .Values.lxcfs.daemonSet.resources | nindent 12 }}
          volumeMounts:
            - name: cgroup
              mountPath: /sys/fs/cgroup
            - name: lxcfs
              mountPath: /var/lib/lxc/lxcfs
              mountPropagation: Bidirectional
            - name: usr-local
              mountPath: /usr/local
            - name: usr-lib64
              mountPath: /lib/x86_64-linux-gnu
            {{- if .Values.lxcfs.daemonSet.lifecycle.postStart.enable }}
            - mountPath: /opt/log/
              name: datalog
              subPathExpr: $(NAMESPACE)/$(POD_NAME)
            - name: remount-script
              mountPath: /opt/container_remount_lxcfs.sh
              subPath: container_remount_lxcfs.sh
            - name: crictl-config
              mountPath: /etc/crictl.yaml
              subPath: crictl.yaml
            - name: cri-socket
              mountPath: /var/run/containerd/containerd.sock
            - name: crictl-bin
              mountPath: /usr/bin/crictl
            {{- end }}
            - name: start-script
              mountPath: /start.sh
              subPath: start.sh
            {{- with .Values.lxcfs.daemonSet.volumeMounts.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
      volumes:
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: usr-local
          hostPath:
            path: /usr/local
        - name: usr-lib64
          hostPath:
            path: /lib/x86_64-linux-gnu
        - name: lxcfs
          hostPath:
            path: /var/lib/lxc/lxcfs
            type: DirectoryOrCreate
        {{- if .Values.lxcfs.daemonSet.lifecycle.postStart.enable }}
        - name: datalog
          hostPath:
            path: {{ .Values.lxcfs.daemonSet.lifecycle.postStart.logPath }}
            type: DirectoryOrCreate
        - name: remount-script
          configMap:
            name: lxcfs-remount-script
            defaultMode: 0777
        - name: crictl-config
          configMap:
            name: lxcfs-crictl-config
        - name: cri-socket
          hostPath:
            path: /var/run/containerd/containerd.sock
            type: Socket
        - name: crictl-bin
          hostPath:
            path: /usr/bin/crictl
            type: File
        {{- end }}
        - name: start-script
          configMap:
            name: lxcfs-start-script
            defaultMode: 0777
        {{- with .Values.lxcfs.daemonSet.volumes.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}