{{- if .Values.lxcfs.daemonSet.lifecycle.postStart.enable }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: lxcfs-crictl-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "chart.labels" . | nindent 4 }}
data:
  crictl.yaml: |
    runtime-endpoint: {{ .Values.lxcfs.configMaps.crictlConfig.endpoint }}
    image-endpoint: {{ .Values.lxcfs.configMaps.crictlConfig.endpoint }}
    timeout: 10
    debug: false
{{- end }}